### PR TITLE
Finished UART-Jetson Communication Protocol

### PR DESCRIPTION
**Pull request by RogerQi**
- Implemented CRC8 MAXIM checksum in shared libraries
- Implemented and tested communication protocol w/ numeric decoding logic. Check out the protocol [here](https://github.com/illini-robomaster/iRM_Vision_2023/blob/roger/crc_comm/docs/comm_protocol.md)
- Tested communication using Macbook + USB to type A and type C board
- Implemented an example checking validity of input and decoding numbers

### CODE REVIEW

**Comment by RogerQi** [comment]
An issue with circular decoding was found. Require more work to make it more robust and be integrated

**Comment by RogerQi** [comment]
This PR is now ready for review. Major changes

- Reworked the entire minipc protocol
- Added stress testing script to mock 200Hz communication and passed (see comments in example/minipc/typeC.cc)

**Comment by Andd54** [comment]
> Check out the protocol [here](https://github.com/illini-robomaster/iRM_Vision_2023/blob/roger/crc_comm/docs/comm_protocol.md)

This Link is broken, please update a new one

**Comment by RogerQi** [comment]
> > Check out the protocol [here](https://github.com/illini-robomaster/iRM_Vision_2023/blob/roger/crc_comm/docs/comm_protocol.md)
> 
> This Link is broken, please update a new one

The original branch was deleted. Please find it here https://github.com/illini-robomaster/iRM_Vision_2023/blob/dev/docs/comm_protocol.md

**Review by Andd54 — APPROVED** [review]
LGTM

**Pull request merged**
